version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hydro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hydro
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./hydro:/hydro/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=hydro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hydro
    depends_on:
      - db